### ISSUE TITLE
consul_agent RUN_DIR should be created in pre-start

### ISSUE THREAD

**Issue by rboykin** [cloudfoundry-incubator/consul-release#44]
The consul_agent agent_ctl script attempts to create the RUN_DIR directory for the consul_agent.  However since agent_ctl is running as user vcap, it cannot create the directory.

Perhaps the RUN_DIR directory should be created in pre-start and subsequently have its ownership changed to vcap:vcap

join_ctl also has code to mkdir and chown for the RUN_DIR directory

**Comment by Amit-PivotalLabs** [comment]
Hi @rboykin 

Can you share some more details about the errors you're seeing?  What version of the release are you deploying, and what stemcell?  If possible, a copy of your manifest with sensitive information redacted, and a paste of your `bosh deploy` output would be helpful.  I believe the `RUN_DIR` lives on ramdisk and is safe to create in the regular `_ctl` script.  I'll have to check with the team, but there was some work we did a while back to minimize what we run as `root`, and there was a reason at the time we couldn't move `RUN_DIR` also into the pre-start.

Thanks,
Amit

**Comment by rboykin** [comment]
consul_agent would not come up even after pre-start was run until I manually did a mkdir -p /var/vcap/sys/run/consul_agent and then chown vcap:vcap.  

Check the agent_ctl script.  It is run as vcap:vcap and it assumes it can mkdir /var/vcap/sys/run/consul_agent.  Bad assumption.

Trying this on a 242 clean deployment.

After doing a monit start consul_agent,
agent_ctl.err.log contents:

[2016-09-15 05:40:56-0500] + main start
[2016-09-15 05:40:56-0500] + mkdir -p /var/vcap/sys/run/consul_agent
[2016-09-15 05:40:56-0500] mkdir: cannot create directory '/var/vcap/sys/run/consul_agent': Permission denied

**Comment by Amit-PivotalLabs** [comment]
Creating the RUN_DIR as is was done intentionally, not based on assumptions.  I'll have to get back to you with details. What stemcell are you on?

**Comment by rboykin** [comment]
I am running cf_nise_installer.  It installs directly on an existing VM.  I also note that other monit jobs create their RUN_DIR's within their pre-start scripts, namely all others (at least in cf_nise_installer) that are started from their monit job as vcap:vcap other than consul_agent.

Sorry, did not mean to insult with the assumption comment.

**Comment by Amit-PivotalLabs** [comment]
We do this in several other places, not just consul_agent:

postgres:
- run as vcap: https://github.com/cloudfoundry/postgres-release/blob/
fd70cecd9e887b1b637da50cfba7a6fbee71c393/jobs/postgres/monit#L4
- create run dir: https://github.com/cloudfoundry/postgres-release/blob/
master/jobs/postgres/templates/postgres_ctl.erb#L61

etcd
- run as vcap: https://github.com/cloudfoundry-incubator/etcd-release
/blob/49727b37f40129dd99515cb3e4d27c49c45d3026/jobs/etcd/monit#L4
- create run dir: https://github.com/cloudfoundry-incubator/etcd-release/
blob/49727b37f40129dd99515cb3e4d27c49c45d3026/jobs/etcd/temp
lates/etcd_ctl.erb#L30

This works with BOSH because it actually sets up /var/vcap/sys/run
differently, I believe it uses a tempfs or something like that.  You'd have
to ask the BOSH community for more details on that, either on
github.com/cloudfoundry/bosh/issues, cf-bosh mailing list (
https://lists.cloudfoundry.org/archives/list/cf-bosh@lists.cloudfoundry.org/),
or #bosh slack (https://cloudfoundry.slack.com/archives/bosh).

We've done it this way due to some combination of factors, namely (a)
pre-start doesn't always run before monit start and (b) we wanted to run
our _ctl script as vcap instead of root.  We had originally put the run_dir
creation in the pre-start script, I'll ask around and try to figure out the
exact issue we hit with that.  I recall we "got lucky" when we found out
BOSH handled tmpfs differently and was safe to create run-dir in the _ctl
script.

Anyone @cloudfoundry-incubator/cf-infrastructure recall the exact details
of this?

/cc @cppforlife

**Comment by rboykin** [comment]
Note that in both the postgres and etcd cases specified as examples above, the RUN_DIR is also created in their respective pre-start scripts:

https://github.com/cloudfoundry/postgres-release/blob/master/jobs/postgres/templates/pre-start.erb#L35

https://github.com/cloudfoundry-incubator/etcd-release/blob/master/jobs/etcd/templates/pre-start.erb#L21

**Comment by Amit-PivotalLabs** [comment]
Good point.  Will take a look.

**Comment by rboykin** [comment]
Thanks much @Amit-PivotalLabs

**Comment by christianang** [comment]
Hi @rboykin,

Took a look and it seems like we should do the mkdir RUN_DIR in both the ctl and pre-start so we have added that: https://github.com/cloudfoundry-incubator/consul-release/commit/351bae9ad0ed38b396b9d328bdbb75e81da481f8.

Thanks.

**Comment by rboykin** [comment]
Thanks @christianang
