### ISSUE TITLE
Monitoring Consul

### ISSUE THREAD

**Issue by giner** [cloudfoundry-incubator/consul-release#63]
Consul has become one of core components of Cloud Foundry release and it would be nice to have a way to monitor it. Consul itself has [telemetry](https://www.consul.io/docs/agent/options.html#telemetry) configuration options however there is no easy way to pass this configuration to consul servers and agents within consul-release.

Are there any plans to implement telemetry options or to make consul-release more extensible in terms of configuration?

**Comment by CAFxX** [comment]
Specifically, we'd be interested in enabling telemetry via statsd to an endpoint we specify. I would recommend, unless there are compelling reasons not to to, to simply instruct confab to pass the telemetry data structure through to the consul config file.

As a slightly more open-ended suggestion: one of our best-practices is to always have a way to allow custom configuration to the components - something that may not seem relevant or useful at first may become a lifesaver down the road.

**Comment by evanfarrar** [comment]
hello @CAFxX and @giner 

This is a good suggestion, I think because of the way the rest of the config.json is currently generated it might be best to expose a new YAML structure to set the statsd address, specifically:
```
properties:
  consul:
    agent:
      telemetry:
        statsd_address: myhost:8125 
```

This would leave us room in the future to pass something more open ended but solve your immediate needs for now. I will schedule this work, but a bit behind other priorities in our backlog.

**Comment by evanfarrar** [comment]
@CAFxX and @giner 

This new property is in consul-release v157 . Are you able to consume that? We can't currently merge this into cf-release because of a bug where consul's links overflow bosh's column width on mysql.
