### ISSUE TITLE
Release 193 does not provide a tgz file

### ISSUE THREAD

**Issue by albertoleal** [cloudfoundry-incubator/consul-release#88]
Hi,

Could you please provide a tgz file for release 193? Our pipelines rely on that and at the moment they're failing because of that. 

Concourse does some caching and we'll need to re-create our workers in order to pick up the same version again. That being said how about releasing 194 and discard 193? 

Thanks,
Alberto and Kura

**Comment by mcwumbly** [comment]
At this point, you should be using 194 as 193 has another obscure issue related to how BOSH compiles releases when an unused package is referenced which is fixed by [this commit](https://github.com/cloudfoundry-incubator/consul-release/commit/fa7051163c1ddf13bcf6021cbb666c28c8de03a7).

In any case, 194 has a tgz: https://github.com/cloudfoundry-incubator/consul-release/releases/tag/v194

**Comment by albertoleal** [comment]
Thanks for the update @mcwumbly 👍
